esphome:
  name: sonoff
  platform: ESP8266
  board: esp01_1m


# Укажите имя вашей Wi-Fi сети и пароль

wifi:
  ssid: "Wi-Fi Name"
  password: "Password"

# Создавать точку доступа если не получается подключится в Wi-Fi сети
# Укажите имя и пароль для точки доступа

  ap:
    ssid: "Sonoff Fallback Hotspot"
    password: "Password"

captive_portal:

# Включить logging
logger:

# Включить Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: "Sonoff Basic Relay"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "Sonoff Basic Green LED"
    output: basic_green_led
    id: led

sensor:
  - platform: wifi_signal
    name: "Sonoff Basic WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Sonoff Basic Uptime"
  
text_sensor:
  - platform: version
    name: "Sonoff Basic ESPHome Version"
